version: "3.8"
services:
  mysql_udf:
    build: .
    container_name: mysql_udf
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: